<<<<<<< HEAD
dev_admin:
    resource: "@DevAdminBundle/Controller/"
    type:     annotation
    prefix:   /

dev_film:
    resource: "@DevFilmBundle/Controller/"
    type:     annotation
    prefix:   /

=======
>>>>>>> re
devschool_admin:
    resource: "@DevschoolAdminBundle/Controller/"
    type:     annotation
    prefix:   /

devschool_biblio:
    resource: "@DevschoolBiblioBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
